version: "3.8"

services:
  postgres:
    container_name: demo-db
    image: postgres
    restart: always
    volumes:
      - ./init-schema/init.sql:/docker-entrypoint-initdb.d/init.sql # Mount the initialization script
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres/postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
