drop table if exists drone;
create table drone
(
    serial_number    varchar primary key,
    model            varchar not null,
    weight_limit     integer not null,
    battery_capacity integer not null,
    state            varchar not null
);

drop table if exists medication;
create table medication
(
    code   varchar primary key,
    "name" varchar,
    weight integer not null,
    image varchar
);

drop table if exists drone_medication;
create table drone_medication
(
    id            integer generated by default as identity primary key,
    drone_id      varchar,
    medication_id varchar not null,
    constraint drone_serial_number_fk_1
        foreign key (drone_id) references drone (serial_number),
    constraint medication_code_fk_2
        foreign key (medication_id) references medication (code)
);